spring.application.name=sal

# Unipile API configurations
unipile.api.base-url=https://api34.unipile.com:16410
unipile.api.key=RsOZhmAf.yBmrkZzXuviXZl01Rsyt4+Vo5XrhSFaw8Qi9k1+Hn50=
unipile.api.auth-domain=auth.sal.com
unipile.api.ambiente=localhost
unipile.account-id=OH0HvmubQmauwdtfr6LM3Q

# SpringDoc OpenAPI configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha


# C6 Checkout (Sandbox)
c6.checkout.base-url=https://baas-api-sandbox.c6bank.info
c6.checkout.client-id=
c6.checkout.client-secret=
c6.checkout.merchant-id=
c6.checkout.default-currency=BRL
